layout_spectrum: 0.222597
name: Ctrlz
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
typography_spectrum: 0.8064516
color:
  brandStrength: 0.7133048
  saturation: 0.1971326
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  lightness: 0.7867383
  rhythmicContrast: 0.6146954
