collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1971326
  brandStrength: 0.7133048
  lightness: 0.7867383
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  rhythmicContrast: 0.6146954
typography_spectrum: 0.8064516
layout_spectrum: 0.4203722
name: Ctrlz
